country_name: "uganda"
ssp_input_file_name: "ssp_inputs_uganda_10Fold_scenario_with_dijis_inputs_and_adj_qmats.csv"
ssp_transformation_cw: "ssp_uganda_transformation_cw_2025_04_21.xlsx"
set_lndu_reallocation_factor_to_zero: true
energy_model_flag: false