country_name: "uganda"
ssp_input_file_name: "ssp_inputs_uganda_20250311.csv"
ssp_transformation_cw: "ssp_uganda_transformation_cw_2025_04_28.xlsx"
set_lndu_reallocation_factor_to_zero: true
energy_model_flag: false